listen_addresses = '*'
port = 5432

wal_level = replica
max_wal_senders = 5
max_replication_slots = 5
wal_keep_size = 128MB

synchronous_commit = on
synchronous_standby_names = 'replica1'

shared_buffers = 256MB
effective_cache_size = 768MB
max_connections = 200

log_min_duration_statement = 200
log_connections = on
log_disconnections = on
