listen_addresses = '*'
port = 5432

hot_standby = on
hot_standby_feedback = on

wal_level = replica
max_connections = 200

shared_buffers = 256MB
effective_cache_size = 768MB

log_min_duration_statement = 200
